---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
```

```{r}
#tmp = read.csv("BioTIMEQuery_24_06_2021.csv")
#save(tmp, file = "BioTIME_data.RData")
load("BioTIME_data.RData")
```

# exploration
```{r}
head(tmp, 50)
```


# filter out to remove the rows without a value for species 

```{r}
tmp2 = tmp %>%
  filter(SPECIES != "sp",
         SPECIES != "spp.",
         SPECIES != "spp") # loss of 2.45%

tmp2 = tmp2 %>%
  filter(!is.na(SPECIES)) # no change
```


```{r}
tmp3 = tmp2 %>%select(GENUS_SPECIES) %>%
  distinct() # obtain list of unique species

# create subset to see if R and slurm script works
tmp3_1 = tmp3[1:4000,] %>% # adjust 4000 to smaller values for faster testing
  as.data.frame() %>%
  rename("GENUS_SPECIES" = ".") 

save(tmp3, file = "taxonomies.RData")
save(tmp3_1, file = "taxonomies_1.RData")
```

# in-situ testing of code
## taxize it to add family
```{r}
library(taxize)

taxize_options(ncbi_sleep = 0.8) # you can adjust this time to prevent api limit exceed

tmp_taxized2 <- classification(tmp3_1$GENUS_SPECIES, db = "ncbi",
                              batch_size = 5) # tap on ncbi db to add taxonomic values to species; recommend setting tmp3_1 to just 5-10 rows for fast results
```

```{r}
extract_family <- function(df) {
  if (is.data.frame(df)) {
   family_row <- df[df$rank == "family", ]
   order_row = df[df$rank == "order", ] 
   class_row = df[df$rank == "class",]
   return(paste(family_row$name, order_row$name, class_row$name,
                sep="_"))
   } else {
   return(NA)
   }
}

ltfem_seedling_families2 <- lapply(tmp_taxized2, extract_family)

ltfem_seedling_families2 <- ltfem_seedling_families2[!sapply(ltfem_seedling_families2, is.na)]

ltfem_seedling_families2 = as.data.frame(ltfem_seedling_families2) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "species")
# 
# ltfem_seedling_families$species =  str_replace_all(ltfem_seedling_families$species,"\\."," ")
# 
# ltfem_seedling_families = ltfem_seedling_families %>%
#   separate(V1, into = c("family", "order"), sep = "_")
```


# extract class and other taxonomic values
this chunk below is for obtaining the results from the slurm job
```{r}

load("tmp_foc.RData")
load("tmp_taxized_slurm.RData")

# run the code below only if the taxize.R script did not did the following post-processing
tmp_foc <- tmp_foc[sapply(tmp_foc, length) > 0]

tmp = as.data.frame(tmp_foc) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "species")

tmp$species =  str_replace_all(tmp$species,"\\."," ")

tmp = tmp %>%
  separate(V1, into = c("family", "order", "class"), sep = "_")

# export tmp to view results
```



